### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dodysw** [armooo/cloudprint#105]
Hi Jason, would you be interested in making cloudprint compatible with Python 3.x? I have made a fork available at https://github.com/dodysw/cloudprint/tree/py3, which was a result of running 2to3 scripts and various tweaks on string/bytes handling that prevented it to work previously, and tested to still work at Python 2.6, 2.7, 3.3, and 3.4 running in Ubuntu 14.04 crouton in ARM based Chromebook (and a quick check on an x86 Ubuntu 14.04 too just to make sure). 

I have not test this at OS X since my thought was OS X is already capable of printing to classic printers without running Google Cloud Print connector. 

Suppose if you want me to submit a pull request then let me know.

**Comment by armooo** [comment]
Python 3 support sounds good to me. The only problem I how to keep it working. With the current lack of test coverage the python 3 support will regress quickly. (I have already  accidentally broke 2.6 support a few times)

**Comment by dodysw** [comment]
OK, are you thinking tests just for making sure changes wont break at different python versions, or a more general unit tests that check more things? And are you expecting contributions for these?

**Comment by armooo** [comment]
I will work on getting some basic tests that mock cups and google working tonight. Once that is done we can enable testing on python3 on your branch and merge it.

**Comment by armooo** [comment]
I did not get as far as I wanted to adding tests but I will add some more tomorrow as well.

**Comment by dodysw** [comment]
Hope you have a good rest, I will make sure to follow this up when you're done.

**Comment by armooo** [comment]
I just merged your py3 branch!

**Comment by michaelarnauts** [comment]
I can't seem to get it to work.

````
$ cloudprint
Traceback (most recent call last):
  File "/usr/local/bin/cloudprint", line 9, in <module>
    load_entry_point('cloudprint==0.13', 'console_scripts', 'cloudprint')()
TypeError: main() missing 1 required positional argument: 'args'
````

**Comment by armooo** [comment]
Sorry about that. I just pushed a fix for the console script entry point.

**Comment by michaelarnauts** [comment]
Awsome, it works now. Thanks for the quick fix.

**Comment by dodysw** [comment]
Thanks. Also, glad now we have some tests written.
