### ISSUE TITLE
UnboundLocalError: local variable 'auth_response' referenced before assignment

### ISSUE THREAD

**Issue by witeshadow** [armooo/cloudprint#106]
Just started using this after my Ubuntu machine was dormant for a number of months. I receive the following error when trying to start it: 

`UnboundLocalError: local variable 'auth_response' referenced before assignment`

Python is 2.7 
Ubuntu 14.04 LTS
cloudprint version in Synaptic: 0.5-0ubuntu1

**Comment by davesteele** [comment]
That will be the least of your problems with 0.5. Version 0.13 is in Wiley Universe, or [here](http://davesteele.github.io/cloudprint-service/).
