### ISSUE TITLE
Out of date firmware

### ISSUE THREAD

**Issue by Linus-007** [armooo/cloudprint#111]
I am receiving a message about out of date firmware every time I use cloudprint.
I am running Ubuntu and printing to an Epson tm-t20ii thermal printer. The Epson THermal Printer is attached to the Ubuntu server via USB. This printer is properly registered in CUPS and I have been using it quite often from Ubuntu and Windows (via shared printer).

The issue only presents itself when I use cloudprint. Is this a cloudprint issue? Obviously the Thermal printer is not a cloud ready printer. 

Email Message: 

"Epson" has out-dated firmware
Hello,

Your recent print job (XXXXX) to Epson could not be retrieved by the printer, because the firmware for this printer is out of date.

To update your printer firmware and continue using Google Cloud Print, follow the instructions on your printer manufacturer's upgrade page.

If you have any questions or issues, please post them to the Google Chrome Forums or contact Epson customer support.

Best regards,
The Google Cloud Print team

**Comment by dodysw** [comment]
Just to add that this issue was discussed 2 years ago: https://productforums.google.com/forum/#!topic/chrome/yF_dEIu2o2M

Seems you need to update the printer firmware to get rid of the email.

**Comment by Linus-007** [comment]
My situation as described is that I have a usb printer that is not a cloud printer. I am using cloudprint to make the printer look like a cloud printer. There is no firmware update to apply. Additionally the thread offers no solution given what I explained. It only affirms that others are having the same issue.

**Comment by dodysw** [comment]
Got it. I can reproduced it. There is an annoying email message every time a print job is sent to this printer. I'll spend some time checking the proxies messages to learn more.

**Comment by dodysw** [comment]
Can you try adding a new cups printer, exactly the same as your existing one for your thermal printer, but don't put "epson" in the printer name? E.g. instead of EPSON_TM-II, use name such as THERMAL or something,

**Comment by Linus-007** [comment]
I created a new CUPS Printer. That worked. Great Idea.

**Comment by armooo** [comment]
Sounds like a "feature" of google's on the server side. Closing this bug.
