### ISSUE TITLE
Cheeseshop is still showing old usage

### ISSUE THREAD

**Issue by brejoc** [armooo/cloudprint#127]
Seems like the [Cheeseshop](https://pypi.python.org/pypi/cloudprint) ist still showing an old usage.

**Comment by davesteele** [comment]
It is [pending](https://github.com/armooo/cloudprint/commit/5c33ff32d9ae753a5d41c1a3f4c504f24d544c2e).

**Comment by brejoc** [comment]
Cleaning up. If you think this should be re-opened, feel free to do so or contact me.
