### ISSUE TITLE
cloudprint will not print

### ISSUE THREAD

**Issue by gearhead** [armooo/cloudprint#36]
The script installs fine. I can install a printer and it shows up on the cloudprint web page. It tries to send a file for printing. With the git version, here, it just shows as 'error' on the web page and is never sent. This is with the cloudprint test page or any other file I attempt to print.

I did find this link which may be related, but since I do not know python, I have no idea what is being discussed: https://productforums.google.com/forum/?fromgroups=#!topic/chrome/6QVEHIrVXEo

**Comment by armooo** [comment]
We now better error reporting. If this still happens please run `cloudprint.py -v` and report a new traceback.
