### ISSUE TITLE
Trouble running cloudprint at boot using /etc/init.d/cloudprint script

### ISSUE THREAD

**Issue by casestudies** [armooo/cloudprint#46]
I'm able to start the script from  the  command line. I get a prompt for Google credentials and it starts up fine.

However, I'm trying to set up an init.d script so it starts up at boot. I've tried a few ways of doing it, but haven't had much luck. I either get python errors or no errors, but after checking if it's running us ps, I find that it's not running.

The closest I believe I came was receiving an error from what  looked like Google saying it failed on a recaptcha requirement.

Also, I noticed that when I created a file for the authorization with email and password, after running the script, the script was empty, as if the script deleted what was in the file...

This works really well, and I'd love to get it to start up on boot as I plan on using this fairly regularly. Thanks!

**Comment by armooo** [comment]
It looks like we have a few init script solutions here, but I am going to leave this as an upstream packaging problem for now. It is also much simpler in our current systemd based world.

**Comment by poldown** [comment]
just an upgrade to mbirth's answer, a more bulletproof cloudprint.conf upstart job would be:
```
start on (filesystem and net-device-up)
stop on shutdown
respawn
respawn limit unlimited
post-stop exec sleep 10

console log

setuid johndoe
env HOME=/home/johndoe
env USER=johndoe

exec /usr/local/bin/cloudprint -f
```
(then the cloudprint python script will be restarted in case of a failure - for exmple, internet connection problem, which crashes the script)

**Comment by davesteele** [comment]
The 'deb8' series of [cloudprint-service](http://davesteele.github.io/cloudprint-service/) has a package with a working sysv init script.

Internet connection problems should not be crashing the script. Do you have a dump?
