### ISSUE TITLE
New job notifications not working

### ISSUE THREAD

**Issue by richvdh** [armooo/cloudprint#48]
My printers are registered no problem, and they fetch and print jobs fine (eventually), but the script never receives any notifications of new jobs over XMPP, so it takes a really long time for the script to wake up and fetch new jobs.

Does this happen for anyone else?

**Comment by armooo** [comment]
It seems like this was a problem with google not sending notifications to users with shared printers. We also have made a lot of XMPP changes. If this is still happening please reopen.
