### ISSUE TITLE
cloudprint receives no notifications

### ISSUE THREAD

**Issue by schertelk** [armooo/cloudprint#49]
When I start the script,  queued jobs are printed.
But when the script is running, no new jobs are printed.
The script remains in function wait_for_new_job
I produced some debug output from the msg function
(removed some start and end tags, the git editor interprets xml, made some xxx in the auth secret)

OUT: stream to="gmail.com" version="1.0" xmlns="http://etherx.jabber.org/streams"
IN: <ns0:features xmlns:ns0="http://etherx.jabber.org/streams" xmlns:ns1="urn:ietf:params:xml:ns:xmpp-sasl"><ns1:mechanisms><ns1:mechanism>X-OAUTH2</ns1:mechanism><ns1:mechanism>X-GOOGLE-TOKEN</ns1:mechanism><ns1:mechanism>PLAIN</ns1:mechanism></ns1:mechanisms></ns0:features>
OUT: auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="X-GOOGLE-TOKEN">AHNjaGVydGVsa0Bnb29nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx5NElhTks4WXU2VUlxbjdRUUZYZ2lnN0Q0
aDFSakM3QW8xZGdnNXFWUHdCVTVrbl80S2wwTXlNQnVhLTdLa1FoM0Vwb2ktaTd1bGxMQndHMHc0
dVk1VnZodTF6N1Y3YUFVUDRNYjFBeXpLTUphMzZLNVp0cjJnMjYtQXF5Qzhjdnp1ZXBJSHQ3OHNl
dllmNENiY2kyUnFfTVdR
</auth
IN: ns0:success xmlns:ns0="urn:ietf:params:xml:ns:xmpp-sasl" 
OUT: s:stream to="gmail.com" version="1.0" xmlns:s="http://etherx.jabber.org/streams" xmlns="jabber:client">
IN: <ns0:features xmlns:ns0="http://etherx.jabber.org/streams" xmlns:ns1="urn:ietf:params:xml:ns:xmpp-bind" xmlns:ns2="urn:ietf:params:xml:ns:xmpp-session"><ns1:bind /><ns2:session />ns0:features
OUT: iq type="set"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>Armooo</resource></bind></iq>
IN: ns0:iq xmlns:ns0="jabber:client" xmlns:ns1="urn:ietf:params:xml:ns:xmpp-bind" type="result"><ns1:bind><ns1:jid>schertelk@googlemail.com/ArmoooF492D62C</ns1:jid></ns1:bind></ns0:iq
OUT: iq type="set" to="schertelk@googlemail.com"><subscribe xmlns="google:push"><item channel="cloudprint.google.com" from="cloudprint.google.com"/></subscribe></iq
IN: ns0:iq xmlns:ns0="jabber:client" from="schertelk@googlemail.com" to="schertelk@googlemail.com/ArmoooF492D62C" type="result" 
OUT:

**Comment by armooo** [comment]
It seems like this was a problem with google not sending notifications to users with shared printers. We also have made a lot of XMPP changes. If this is still happening please reopen.
