### ISSUE TITLE
ERROR: Could not Connect to Cloud Service. Will Try again in 60 Seconds

### ISSUE THREAD

**Issue by graemev** [armooo/cloudprint#52]
Just installed version 0.10 . Problems have been with 0.9.

I bought my daughter a chromebook . I think every print she has done I've needed to spend about an hour fixing/restarting bits of print.

I have a 'dreamplug' (wheezy) running 24 hours a day ... it runs could cloudprint as a daemon. Usually before it can print I need to restart it (at least) . Today I also had to use -l (logooff). I have  a cron.daily which restarts cloudprint once per day (as it seemed just stop working if left up for many days) . The init script I use contains:

        echo -n "Starting Google Cloud Print: "
        sudo -u $USER cloudprint -d -p $PIDFILE

I have a firewall ... so port 993 cannot get IN (in general NO new incoming traffic is allowed)

So the issues I have are:

1: I'm not sure what is happening WRT msg etc ... so I THINK you are storing a token of some sort ... so it does not actually logon each time? (a guess) ... I did have versions of init.d scripts with -a option .. but I discovered it was being ignored
[ So an outline of what is happening would be good]
I gather there is a poll and a push mode for google print

2: I suspect the failure message I see above indicates the 'token' had expired ... so I needed to logoff/logon again ..... it would help if there were some error message?
[ since I don't know what supposed to happen on the protocol ... I have to guess as what the failure is ... so assuming I guessed right ... it would be nice if this said something like "...failed to authenticate with existing token , you need to logout and login again "

**Comment by armooo** [comment]
Cloudprint now uses OAuth2 so this should not be a problem.
