### ISSUE TITLE
Any way to get this working in Windows?

### ISSUE THREAD

**Issue by benze** [armooo/cloudprint#53]
I can't seem to find a pycups package anywhere for Windows.  I was hoping cygwin or cygwin-ports would have something, but nothing there.

Any chance someone might know if there is a way to get this working under windows, or am I completely SOL.

Thanks,

Eric

**Comment by armooo** [comment]
I am not aware of anyone running this on windows. Pycups requires having the cups libraries. The only way I can think of to do that is use use cygwin but I don't think it will be a simple process.
