### ISSUE TITLE
rest.RESTException: REST Error:404

### ISSUE THREAD

**Issue by robert-s** [armooo/cloudprint#54]
I have been unable to use cloudprint for over a year now.  The daemon crashes when I print anything.  The error message has now changed.  Can anyone help here - I've abbreviated the error message.  I'm using gentoo amd64 with CUPS.

 /usr/lib/cloudprint/cloudprint.py
Updated Printer MFC-7420
Updated Printer CUPS-PDF
Traceback (most recent call last):
  File "/usr/lib/cloudprint/cloudprint.py", line 388, in <module>
    main()
  File "/usr/lib/cloudprint/cloudprint.py", line 384, in main
    process_jobs(cups_connection, cpp, printers)
  File "/usr/lib/cloudprint/cloudprint.py", line 314, in process_jobs
    process_job(cups_connection, cpp, printer, job)
  File "/usr/lib/cloudprint/cloudprint.py", line 307, in process_job
    cpp.fail_job(job['id'])
  File "/usr/lib/cloudprint/cloudprint.py", line 224, in fail_job
    { 'X-CloudPrint-Proxy' : 'ArmoooIsAnOEM' },
  File "/usr/lib/cloudprint/cloudprint.py", line 107, in f
    r = attr(*arg, **karg)
  File "/usr/lib64/cloudprint/rest.py", line 105, in post
    return self.rest_call('POST', path, data, content_type, headers, response_type)
  File "/usr/lib64/cloudprint/rest.py", line 88, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
rest.RESTException: REST Error:404
Message: <!DOCTYPE html><html lang=en><meta charset=utf-8><title>Error 404 (Not Found)!!1</title><style>*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKsAAADVCAMAAAAfHvCaAAAAGFBMVEVYn%2BH%2F%2F

[..]

%2FzufdnZtz7PrrevDZ03GPAaJDjbRA8dGsW6X6cgNmAhSEG%2FUiY%2Fsfiv02O7iVu1LunAAAAAElFTkSuQmCC);display:block;height:55px;margin:0 0 -7px;width:150px}* > #g{margin-left:-2px}#g img{visibility:hidden}* html #g img{visibility:visible}*+html #g img{visibility:visible}</style><a href=//www.google.com/ id=g><img src=//www.google.com/images/logo_sm.gif alt=Google></a><p><b>404.</b> <ins>That’s an error.</ins><p>The requested URL was not found on this server. <ins>That’s all we know.</ins>

**Comment by armooo** [comment]
I am not sure why the API call to report a job as failed would 404. If this is still happening please reopen.
