### ISSUE TITLE
ERROR, then print job URL

### ISSUE THREAD

**Issue by ryanshea** [armooo/cloudprint#82]
I had cloudprint working correctly, but that was short lived. Cups printers work fine, and when I run cloudprint in the forground, even with the -v option I have no idea what is happening. 

I drilled into the egg and there is a 19-line try: section with a catchall except: in process_job so really anything could be happening.

Am I better off just using Chrome to accomplish the goal of cloudprint on Linux?

**Comment by armooo** [comment]
We now log errors after the max retries.
