### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by davesteele** [armooo/cloudprint#84]
With d55435a5, I no longer get any logging from cloudprint in daemon mode. sysloghandler defaults to UDP port 514, but my default Debian sid rsyslog configuration has that UDP port disabled.

A more elegant fix for #78 may be called for - perhaps an option to set the logging destination differently than '/dev/log'.

My installation has also picked up the habit of printing 3-5 copies of everything sent through Cloud Print, regardless of logging settings. The print interface does not offer #copies setting. Local prints do not have that problem. Logging (when configered to work) shows only one job printed. I don't know if this relates.

**Comment by armooo** [comment]
@davesteele I don't see a patch reverting d55435a in the current deb packaging. Is this still required?

**Comment by davesteele** [comment]
cloudprint-service, using systemd, no longer uses daemon mode, so it is not important to me personally.

It looks like Debian still disables the UDP port by default. A command line option may be called for, to resolve FreeBSD vs. Debian needs.

**Comment by davesteele** [comment]
On second thought, I'll resolve this with a patch for Debian, adding the /dev/log reference.

**Comment by davesteele** [comment]
Resolved with https://github.com/davesteele/cloudprint-service/commit/9ac1e8c4f3b7f3d6dbaf0e08e7a1f9fe12bcecb2
