### ISSUE TITLE
Better description needed in README.md

### ISSUE THREAD

**Issue by jeffbrl** [armooo/cloudprint#86]
I think the README would benefit from an overview paragraph that describes what the software does. My interpretation based on a brief browse of the source is that it provides a cloud print connector for "classic" printers to eliminate the need to install chrome on a headless linux server.

I have successfully installed the software and its dependencies. My print jobs get stuck in queued mode. I also encounter this problem with the XP connector, so this clearly unrelated to cloudprint. Once I get the software working, I'd be glad to submit a PR if the maintainers believe a brief overview would be nice to have.

**Comment by armooo** [comment]
I will accept a PR adding a overview to the description. But I am closing this bug because I am not going to be able to get to it.

**Comment by jeffbrl** [comment]
@armooo, you merged my PR #87 a few weeks back. I think the README is more clear now. Thank you.
