### ISSUE TITLE
Keepalive timer doesn't decrease - do not know if it is working

### ISSUE THREAD

**Issue by benze** [armooo/cloudprint#94]
I've been having some trouble with cloudprint actively receiving new jobs.  If there is something in the queue when it is launched, it prints them fine, but once running, if I submit new jobs, they don't seem to be recognized.

When I looked at the syslog, I notice that the keepalive log never seems to decrease, and I don't actually see any keepalive sent:

```
Apr  8 16:20:26 TimeMachine cloudprint.py: <<<  
Apr  8 16:20:26 TimeMachine cloudprint.py: 600.000217 seconds until next keepalive
Apr  8 16:25:28 TimeMachine cloudprint.py: <<<  
Apr  8 16:25:28 TimeMachine cloudprint.py: 600.000190 seconds until next keepalive
Apr  8 16:30:30 TimeMachine cloudprint.py: <<<  
Apr  8 16:30:30 TimeMachine cloudprint.py: 600.000096 seconds until next keepalive
Apr  8 16:35:31 TimeMachine cloudprint.py: <<<  
Apr  8 16:35:31 TimeMachine cloudprint.py: 600.000092 seconds until next keepalive
Apr  8 16:40:34 TimeMachine cloudprint.py: <<<  
Apr  8 16:40:34 TimeMachine cloudprint.py: 600.000154 seconds until next keepalive
Apr  8 16:45:35 TimeMachine cloudprint.py: <<<  
Apr  8 16:45:35 TimeMachine cloudprint.py: 600.000052 seconds until next keepalive
Apr  8 16:50:37 TimeMachine cloudprint.py: <<<  
Apr  8 16:50:37 TimeMachine cloudprint.py: 600.000131 seconds until next keepalive
Apr  8 16:55:39 TimeMachine cloudprint.py: <<<  
Apr  8 16:55:39 TimeMachine cloudprint.py: 600.000149 seconds until next keepalive
Apr  8 17:00:41 TimeMachine cloudprint.py: <<<  
Apr  8 17:00:41 TimeMachine cloudprint.py: 600.000073 seconds until next keepalive
Apr  8 17:05:43 TimeMachine cloudprint.py: <<<  
Apr  8 17:05:43 TimeMachine cloudprint.py: 600.000318 seconds until next keepalive
```

I would have expected to see the # seconds decrease as well as an actual keepalive signal sent.

I'm running on Ubuntu 12.04 and it is launched using the following command:
```
/usr/bin/python /usr/sbin/cloudprintd -v -d -u -a /var/lib/cloudprintd/authfile -p /var/run/cloudprint.pid
```

**Comment by davesteele** [comment]
You're right about there being a problem. There is a log message associated with sending the keepalive, and you're not seeing it. It looks like there is a race condition involving _nextkeepalive in xmpp.py await_notifications(). I'd say that _read_socket() should not update _nextkeepalive, or should only do it if data is received.

**Comment by davesteele** [comment]
Upon reflection, the code is probably right as is. The time is reset whenever data is received. I'm going to try the above strategy anyway, in [cloudprint-service](http://davesteele.github.io/cloudprint-service/), to see if it addresses my occasional xmpp dropouts.

**Comment by benze** [comment]
@davesteele - Does cloudprint-service not just use armooo's cloudprint.py?  Now that you mention it, I am not entirely sure if I am using cloudprint-service or not.

**Comment by davesteele** [comment]
It mostly keeps up with the unreleased commits upstream in the release, but there are a number of unique patches.

**Comment by armooo** [comment]
```
Apr  8 16:40:34 TimeMachine cloudprint.py: <<<
```
This log line looks like the select is returning a socket ready for read and the we are reading whitespace from the socket. My guess is the server is also sending keepalives with a 600 second interval.

**Comment by davesteele** [comment]
Yes. There are keepalives defined in both directions, and the downstream ones come faster. This is expected behavior.
