### ISSUE TITLE
Printer always shows up as only accepting application/pdf

### ISSUE THREAD

**Issue by bmccarthy** [armooo/cloudprint#98]
This is more of a question than a bug (i think).

When setting up my printer with this cloudprint program, it shows the printer as only accepting content types of "application/pdf".  

When trying to print borderless pictures, google print seems to ignore the "StpBorderless=True" and "StpiShrinkOutput=Expand" options I set through the google print UI (these options are labeled as something else in the google print UI).  

The file I am trying to print is a jpg, and when it gets sent to print, google appears to convert it to pdf (ignoring the borderless options above I think), and than when cloudprint receives the pdf, the options it sends to the printer to make it borderless don't seem to matter since it is a pdf with borders in it already.

Do all printers set up with cloudprint only display as accepting only "application/pdf" and not any image types?  

I am making an assumption that if cloudprint set up the printer in google as accepting image types, it would work, but I could be wrong.

**Comment by armooo** [comment]
It sounds like it should work from the docs. Adding a comma-separated list of content types as `content_types ` in the `add_printer` and `update_printer` methods should would.
